feat: Geocoder autocompletion
dverbovyi/angular-heremaps pull request #12
Opened 2017-07-10 13:09 UTC by aanev

Add geocodeAutocomplete and findLocationById methods to HereMapsAPIService public API.

2017-07-11 13:06 UTC, dverbovyi commented
@aanev thanks for your pull request

Your API changes would not be spread via map-api instance, because you need to add this API via MapProxy like here
https://github.com/dverbovyi/angular-heremaps/blob/master/src/heremaps.directive.js#L165

2017-07-11 13:09 UTC, dverbovyi requested changes

2017-07-11 13:09 UTC, dverbovyi commented on src/providers/api.service.js
> +        var autocompleteUrl = protocol + '://autocomplete.geocoder.cit.api.here.com/6.2/suggest.json',
@aanev please move an url to CONFIG constant above of this file here: https://github.com/dverbovyi/angular-heremaps/blob/master/src/providers/api.service.js#L19

2017-07-11 13:09 UTC, dverbovyi commented on src/providers/api.service.js
> +        var locationUrl = protocol + '://geocoder.cit.api.here.com/6.2/geocode.xml',
@aanev please move an url to CONFIG constant above of this file here: https://github.com/dverbovyi/angular-heremaps/blob/master/src/providers/api.service.js#L19

2017-07-14 05:55 UTC, aanev commented
@dverbovyi I was thinking that these changes should not be included in HereMapsDirective. Rather the user will be able to choose to use them as a service in order to provide text-box auto-completion. And then the results can be visualized in the HereMapsDirective.

2017-07-17 07:27 UTC, dverbovyi approved these changes

2017-07-17 07:27 UTC, merged

2017-07-17 08:28 UTC, dverbovyi commented
@aanev your PR was successfully released https://github.com/dverbovyi/angular-heremaps/releases/tag/v0.1.6

and published to npm https://www.npmjs.com/package/angular-heremaps

Thanks for contribution